require("bfswrd.plugins.bufferline")
require("bfswrd.plugins.nvim-tree")
require("bfswrd.plugins.auto")
require("bfswrd.plugins.cloak")
require("bfswrd.plugins.colors")
-- require("bfswrd.plugins.fugitive")
require("bfswrd.plugins.telescope")
require("bfswrd.plugins.treesitter")
require("bfswrd.plugins.undotree")
require("bfswrd.plugins.luaship")
require("bfswrd.plugins.cmp")
require("bfswrd.plugins.lspconfig")
require("bfswrd.plugins.mason")
require("bfswrd.plugins.null-ls")
require("bfswrd.plugins.gitsigns")
